### PR TITLE
Add a try catch to cheerio, some sequences of 'id' selectors break the parser.

### LINKED ISSUE #12: When anchor contains a '.%' sequence: `Error: TypeError: Cannot read property '0' of null`
This is an upstream bug in the CSS selector parser Cheerio uses (`css-what`).

An example hash fragment: '#12.%20fail'  is incorrectly parsed as an 'id', and then a 'class' because of the '.%20' character in the hash fragment, which is incorrectly handled.

1. https://html.spec.whatwg.org/multipage/browsers.html#scroll-to-fragid

Turtles all the way down.

### PR DESCRIPTION
**Pull request by samgiles**
Handle the failure case gracefully.

Closes #12

@wilsonpage r?

### CODE REVIEW

**Comment by wilsonpage** [comment]
@samgiles we've got an unrelated failure for google-play description parsing. Suggests the markup may have changed. Feel free to `.skip()`, or fix if you have time :)

**Comment by wilsonpage** [comment]
If you skip can you file a bug :)

**Comment by wilsonpage** [comment]
r+

**Comment by samgiles** [comment]
That's weird.... - it works locally, I'll look in a separate issue.

**Comment by wilsonpage** [comment]
Ah, it might be because the app store descriptions are different in US/UK
and the Travis box is in the US.

**Pull request merged**
