### PR TITLE
Replaced our own joinURL() with node url.resolve() (fixes #3)

### LINKED ISSUE #3: Icon 404 at https://github.com/mozilla/project_haiku.iot
Moved from https://github.com/mozilla-magnet/magnet-metadata-service/issues/48

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
@arcturus r?

**Comment by arcturus** [comment]
r+ :)

When installing in the server the new version, can you be sure to collect the logs before restarting?

**Comment by wilsonpage** [comment]
>When installing in the server the new version, can you be sure to collect the logs before restarting?

@arcturus can you clarify what that means exactly

**Comment by arcturus** [comment]
When you run pm2 restart, I think we are losing the logs of the process, I want to keep them. Dump them to a file or something similar.

**Pull request merged**
